Fix send email fail issue caused by review bot

diff --git a/.github/workflows/send-email.yml b/.github/workflows/send-email.yml
--- a/.github/workflows/send-email.yml
+++ b/.github/workflows/send-email.yml
@@ -2,14 +2,51 @@ name: Send PR Diff Patch
 
 on:
   issue_comment:
+    branches:
+      - "main" 
+      - "main-aie" 
     types: [created]
   pull_request_review:
+    branches:
+      - "main" 
+      - "main-aie"
     types: [submitted]
 
 jobs:
+  check-target-branch:
+    runs-on: self-hosted
+    outputs:
+      is_correct_branch: ${{ steps.check-branch.outputs.is_correct_branch }}
+      pr_number: ${{ steps.set-pr-number.outputs.pr_number }}  # Output the PR number here for other jobs
+
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v3
+
+    - name: Set PR Number
+      continue-on-error: true
+      id: set-pr-number
+      run: |
+        if [ "${{ github.event_name }}" == "issue_comment" ]; then
+            echo "::set-output name=pr_number::${{ github.event.issue.number }}"
+        elif [ "${{ github.event_name }}" == "pull_request_review" ]; then
+            echo "::set-output name=pr_number::${{ github.event.pull_request.number }}"
+        fi
+
+    - name: Retrieve PR Data for Branch Check
+      id: check-branch
+      env:
+        GH_TOKEN: ${{ secrets.GHB_TKN }}
+      run: |
+        PR_DATA=$(gh api repos/${{ github.repository }}/pulls/${{ steps.set-pr-number.outputs.pr_number }})
+        TARGET_BRANCH=$(echo "$PR_DATA" | jq -r '.base.ref')
+        echo "::set-output name=is_correct_branch::$(echo "$TARGET_BRANCH" | grep -E '^(main|main-aie)$')"
+
   check-approvals:
     runs-on: self-hosted
-
+    needs: check-target-branch
+    if: needs.check-target-branch.outputs.is_correct_branch
+    
     outputs:
       all_conditions_met: ${{ steps.approval-check.outputs.all_conditions_met }}
       first_approver_name: ${{ steps.approval-check.outputs.first_approver_name }}
@@ -32,6 +69,8 @@ jobs:
     - name: Retrieve PR Data for Issue Comments
       if: github.event_name == 'issue_comment'
       id: retrieve-pr-data
+      env:
+        GH_TOKEN: ${{ secrets.GHB_TKN }}
       run: |
         PR_DATA=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.issue.number }})
         PR_BASE_REF=$(echo "$PR_DATA" | jq -r .base.ref)
@@ -55,10 +94,17 @@ jobs:
         echo "APPROVED_REVIEWERS are $APPROVED_REVIEWERS"
 
         # Check if there is at least one approval
-        if [ $(echo "$APPROVED_REVIEWERS" | jq 'length') -eq 0 ]; then
-            echo "No valid approvals found."
-            gh pr comment $PR_NUMBER --body "**[GITHUB ACTIONS]** :x: The process of generating and sending the patch email failed. Atleast one reviewer approval needed! :x: ."
+        if [ $(echo "$APPROVED_REVIEWERS" | jq 'length') -le 1 ]; then
+            echo "Need one developer approval and review bot approval, but not found."
+            gh pr comment $PR_NUMBER --body "**[GITHUB ACTIONS]** :x: The process of generating and sending the patch email failed. Atleast one developer reviewer and review bot approval needed! :x: ."
             exit 1
+        fi
+        
+        # Check if review bot approved
+        if ! echo "$APPROVED_REVIEWERS" | jq -r '.[]' | grep -q 'bot'; then
+          echo "Review bot approvals not found."
+          gh pr comment $PR_NUMBER --body "**[GITHUB ACTIONS]** :x: The process of generating and sending the patch email failed. Review bot approval needed! :x: ."
+          exit 1
         fi
 
         # Fetch the login of the first approver
@@ -228,6 +274,10 @@ jobs:
         APPROVED_REVIEWERS_LOGINS=$(echo "$REVIEWS_JSON" | jq -r '[.[] | select(.state=="APPROVED") | .user.login] | unique | .[]')
 
         for LOGIN in $APPROVED_REVIEWERS_LOGINS; do
+        # bypass the review bot which contain the name "bot"
+          if [[ "$LOGIN" == *bot* ]]; then
+            continue
+          fi
           EMAIL="${LOGIN}@amd.com"
           CC_EMAILS_ARRAY+=( "--cc" "${EMAIL}" )
         done
